spring.application.name=TienDatShop
#Database setting
spring.datasource.url=jdbc:postgresql://db.etncklbtvogzrbiykjpf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=nguyenanhduy123
# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Redis settings
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=6000
spring.data.redis.database=0
# VNPay settings
vnpay.tmn-code=ATRFAKWN
vnpay.hash-secret=3IXB1BDHXOJCY2FX14U1BLS545E4S48A
vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/vnpay-return
app.frontend.url=http://localhost:4200